version: '3.8'

services:
  openresty:
    image: sppo55/openresty:1.27.1.1-1-alpine-uuid
    # environment:
      # - JAEGER_ENDPOINT=http://jaeger:14268/api/traces    
      # - ZIPKIN_ENDPOINT=http://172.19.0.5:9411/api/v2/spans
    container_name: openresty
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./w3c_trace.lua:/usr/local/openresty/lualib/w3c_trace.lua:ro
      - ./jaeger_exporter.lua:/usr/local/openresty/lualib/jaeger_exporter.lua:ro
    networks:
      - app-network      

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    environment:
      - JAEGER_ENDPOINT=http://jaeger:14268/api/traces
      - PORT=8080
    container_name: gateway  
    ports:
      - "8080:8080"
    networks:
      - app-network

  webhook:
    build:
      context: ./webhook
      dockerfile: Dockerfile
    environment:
      - JAEGER_ENDPOINT=http://jaeger:14268/api/traces
      - LOG_LEVEL=info
      - METRICS_RETENTION=24h
      - PORT=8081
    container_name: webhook
    ports:
      - "8081:8081"
    networks:
      - app-network

  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"  # UI
      - "14268:14268"  # Collector HTTP
      - "9411:9411"    # Zipkin collector
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - app-network

  # debian:
  #   container_name: debian
  #   image: debian:bullseye-slim
  #   command: ["sleep", "infinity"]
  #   networks:
  #     - app-network


networks:
  app-network:
    driver: bridge
