-- 創建遊戲記錄表
CREATE TABLE IF NOT EXISTS games (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    game_id VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uk_game_id (game_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
